project:
  type: website
  output-dir: docs

website:
  title: "Jin Niu"
  favicon: favicon.png
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: CV_Niu_2026.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body: scripts.html
    toc: true

editor:
  render-on-save: true

resources:
     - googled57281e36b9e62f4.html